# Generated by Django 5.0.4 on 2024-05-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_co", "0002_comment_created_at_post_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
