# Generated by Django 5.0.4 on 2024-05-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_co", "0004_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=30),
        ),
    ]
