# Generated by Django 5.0.4 on 2024-05-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_co", "0005_alter_post_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.TextField(max_length=30),
        ),
    ]
