# Generated by Django 5.0.4 on 2024-05-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_co", "0008_alter_post_content_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(default=None, max_length=30),
        ),
    ]
